### ISSUE TITLE
Error in battery: Failed to read 'power_now'.

### ISSUE THREAD

**Issue by farwayer** [MaxVerevkin/swaystatus#14]
From time to time, when connecting / disconnecting power supply to the laptop, an error occurs `Error in battery: Failed to read 'power_now'. (Cause: No such device (os error 19))`

**Comment by MaxVerevkin** [comment]
Can you try [`dbg` branch](https://github.com/MaxVerevkin/swaystatus/tree/dbg)? It should print a little more info to the stderr, so you can log it into a file with:
```
status_command "path_to_binary 2>> /tmp/bar-log"
```

**Comment by farwayer** [comment]
Sure [log.txt](https://github.com/MaxVerevkin/swaystatus/files/7705985/log.txt)

**Comment by farwayer** [comment]
The error only happens when I connect / disconnect the charger

**Comment by MaxVerevkin** [comment]
Well, I don't have a better idea than just ignore IO errors and pretend the file is not there at all. I tried that on `dbg` branch.

**Comment by farwayer** [comment]
Thanks, the error is gone. But I found another issue when the battery is full charged.
```
Error in battery: Failed to render full text. (Cause: Placeholder with name 'time' not found)
```

My battery block config:
```
[[block]]
block = "battery"
interval = 1
format = "$percentage $time"
full_format = "$percentage"
```

**Comment by MaxVerevkin** [comment]
I forgot to mention this in the docs, but that's the desired behavior: when the battery is fully charged time is upsent because it has no meaning. In order to just hide the time when battery is full you can use `$percentage{ $time|}`. You can also hide everything with `$percentage $time|`.

**Comment by MaxVerevkin** [comment]
Does this happen randomly or every time you restart the bar? Temporarily, you can escape this error by using `$percentage{ $time|}`. And by the way, what is your kernel version?

**Comment by MaxVerevkin** [comment]
Can you share the output of `cat /sys/class/power_supply/BAT0/status` (the path might be slightly different for you). For me it sometimes reports "Unknown", but if i connect / disconnect my power supply a few times it will start working again. Maybe that's because my battery is almost dead.

And that should be added to the docs: If the state is unknown, the usual format template is used, but `time` placeholder is missing.

**Comment by farwayer** [comment]
> For me it sometimes reports "Unknown"

Changing/Discharging in my case. "Unknown" never happens. Look like this is random issue.
`$percentage{ $time|}` helped.
I'm using `5.15.7-1-ck-generic-v4`

**Comment by MaxVerevkin** [comment]
Merged the changes into master
