### ISSUE TITLE
Create upstream branch

### ISSUE THREAD

**Issue by ammgws** [MaxVerevkin/swaystatus#15]
It might be a good idea to create an async branch upstream and continue the work there. Lately we've got some new contributors, and in general there are more eyes over there that could possibly help out. What do you think?

**Comment by MaxVerevkin** [comment]
Yes, I've been thinking about this. I haven't done this already because I have full control over this repo and I can experiment with gh-pages and stuff. But in general I agree.

**Comment by ammgws** [comment]
I prepared one here: https://github.com/greshake/i3status-rust/tree/async

Bumped ver to 0.3 as well

**Comment by cfsmp3** [comment]
Can I suggest instead that the current version number is bumped and simultaneously an official release is made? (the version number was bumped some commits ago but there was no release). This would help with packaging.

And then - just jump to the async work with both feet? I personally don't love separate branches, as new people will target master and whatever is new will require porting to async.

So just making an executive decision like "0.20.9 is the final non-async, 0.30.0 will be the first async" would help a lot with releases, packaging, and migration to an async world.

**Comment by MaxVerevkin** [comment]
Also true. I wanted to release 0.20.8 after https://github.com/greshake/i3status-rust/pull/1375 is merged. @ammgws what do you think?

**Comment by cfsmp3** [comment]
> Also true. I wanted to release 0.20.8 after [greshake/i3status-rust#1375](https://github.com/greshake/i3status-rust/pull/1375) is merged. @ammgws what do you think?

But let's skip 0.20.8 and jump to 0.20.9. 0.20.8 (the number I mean) is polluted as a result of having bumped it without making a formal release, so there's some binaries and call themselves 0.20.8 but that are on an earlier commit than master...

**Comment by ammgws** [comment]
> I wanted to release 0.20.8 after [greshake/i3status-rust#1375](https://github.com/greshake/i3status-rust/pull/1375) is merged. 

Sounds fine to me.

> But let's skip 0.20.8 and jump to 0.20.9. 0.20.8 (the number I mean) is polluted as a result of having bumped it without making a formal release, so there's some binaries and call themselves 0.20.8 but that are on an earlier commit than master...

That's a bit strange - packages should be building off a tag, and 0.20.8 hasn't been tagged.

> I personally don't love separate branches, as new people will target master and whatever is new will require porting to async.

The only reason it would be separate for now is because the only person working on it is @MaxVerevkin, and we cannot make any guarantees about when it will be ready. It's pretty close right now, but IIRC there are some things to figure out wrt widgets/formatting and finalising ports of the remaining blocks.

**Comment by cfsmp3** [comment]
> 
> That's a bit strange - packages should be building off a tag, and 0.20.8 hasn't been tagged.

In the case of regolith we needed the rofication block, so I packaged it once we got it (and a few other things I wanted). 

> The only reason it would be separate for now is because the only person working on it is @MaxVerevkin,

If it's decided that async is the way to go, it seems reasonable to make the migration a "theme" for the next version and join Max in the effort, no?

**Comment by ammgws** [comment]
> > That's a bit strange - packages should be building off a tag, and 0.20.8 hasn't been tagged.
> 
> In the case of regolith we needed the rofication block, so I packaged it once we got it (and a few other things I wanted).

That's unfortunate :laughing: We could make a staged release from 0.20.8 to 0.20.9 out of compassion ;)

> > The only reason it would be separate for now is because the only person working on it is @MaxVerevkin,
> 
> If it's decided that async is the way to go, it seems reasonable to make the migration a "theme" for the next version and join Max in the effort, no?

As much as I would like to, unfortunately I cannot commit to that, hence not being in a position to make guarantees, and also do not want to put any pressure on Max either.

**Comment by xvkdev** [comment]
> That's unfortunate laughing We could make a staged release from 0.20.8 to 0.20.9 out of compassion ;)

That would help :-) Not regolith at this point (well, we have a working package :-) ) but in general. I'm also working on getting it to Debian.

At the rate it's progressing I'm not sure it will make it into Bookworm but I'll try.

> As much as I would like to, unfortunately I cannot commit to that, hence not being in a position to make guarantees, and also do not want to put any pressure on Max either.

That's fair. 
Personally the only thing I'm missing is a working -on my system- keyboard layout block so I might just try to help Max and learn some async rust while I'm at at it.

**Comment by cfsmp3** [comment]
> That's unfortunate laughing We could make a staged release from 0.20.8 to 0.20.9 out of compassion ;)

That would help :-) Not regolith at this point (well, we have a working package :-) ) but in general. I'm also working on getting it to Debian.

At the rate it's progressing I'm not sure it will make it into Bookworm but I'll try.

> As much as I would like to, unfortunately I cannot commit to that, hence not being in a position to make guarantees, and also do not want to put any pressure on Max either.

That's fair. 
Personally the only thing I'm missing is a working -on my system- keyboard layout block so I might just try to help Max and learn some async rust while I'm at at it.

**Comment by MaxVerevkin** [comment]
Actually, I think it might make sense to release 0.21.0 because there are two new blocks and five deprecation warnings.

**Comment by ammgws** [comment]
Sure why not.

**Comment by cfsmp3** [comment]
@ammgws I assume it's you who has to press the red button for it to happen? :-)

It would be really convenient. We're automating the .deb creation for it actually, so while getting the Debian package actually available on Debian's repo will take a bit, Debian/Ubuntu packages will be immediately available on regolith's ppa.

**Comment by ammgws** [comment]
Max should be able to as well.

**Comment by MaxVerevkin** [comment]
@cfsmp3 ~~I really want #1375 to get merged before the release, will do some investigation later today.~~ There might be an issue with `sensors`, so I pushed a release without it. There will be a new release before the merge of async stuff anyway.

**Comment by MaxVerevkin** [comment]
@ammgws will it be OK to setup github pages that point to the docs generated by the `async` branch?

**Comment by ammgws** [comment]
From what I see in this repo the only links to the github pages are ones you placed there yourself, so I guess it should be fine when viewing the master branch, right?

**Comment by ammgws** [comment]
Also do we have permissions to setup github pages? I think only the repo owner can set it up

**Comment by MaxVerevkin** [comment]
> Also do we have permissions to setup github pages? I think only the repo owner can set it up

Then I suppose we have to ask @greshake to set it up.

By the way, are branches `v0.14.6`, `v0.14.7` and `0.13.x-release` used somehow?

**Comment by ammgws** [comment]
I think those were used for releases, so might better to leave them.
