### ISSUE TITLE
weather: invalid format if temp in 0..1 range?

### ISSUE THREAD

**Issue by farwayer** [MaxVerevkin/swaystatus#17]
![2022_01_19T21 55 21](https://user-images.githubusercontent.com/2343101/150232626-f1a732ee-d712-43d1-a235-0aed9520a71c.png)

**Comment by MaxVerevkin** [comment]
I assume that's 469 millidegrees :laughing: 

[You can disable the SI prefix](https://maxverevkin.github.io/swaystatus/swaystatus/formatting/index.html#eng---format-numbers-using-engineering-notation): `$temp.eng(2,auto,!1)`

**Comment by farwayer** [comment]
Much better now, thanks :)

**Comment by MaxVerevkin** [comment]
To be fair it should probably the the default setting for degrees.
